name: firebase_storage_web
description: The web implementation of firebase_storage
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage_web
version: 3.9.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.29
  async: ^2.5.0
  firebase_core: ^2.29.0
  firebase_core_web: ^2.15.0
  firebase_storage_platform_interface: ^5.1.16
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: '>=0.13.0 <2.0.0'
  meta: ^1.8.0
  web: ^0.5.1

dev_dependencies:
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseStorageWeb
        fileName: firebase_storage_web.dart
