name: firebase_messaging
description: Flutter plugin for Firebase Cloud Messaging, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
homepage: https://firebase.google.com/docs/cloud-messaging
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging
version: 14.8.1

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.1.3'

dependencies:
  firebase_core:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  firebase_messaging_platform_interface:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging_platform_interface
  firebase_messaging_web:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging_web
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.messaging
        pluginClass: FlutterFirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin
      macos:
        pluginClass: FLTFirebaseMessagingPlugin
      web:
        default_package: firebase_messaging_web
