name: firebase_crashlytics
description:
  Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the
  Firebase console.
version: 3.5.1
homepage: https://firebase.google.com/docs/crashlytics
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.1.3'

dependencies:
  firebase_core:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  firebase_crashlytics_platform_interface:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/firebase_crashlytics/firebase_crashlytics_platform_interface
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.crashlytics
        pluginClass: FlutterFirebaseCrashlyticsPlugin
      ios:
        pluginClass: FLTFirebaseCrashlyticsPlugin
      macos:
        pluginClass: FLTFirebaseCrashlyticsPlugin
