name: firebase_crashlytics_platform_interface
description: A common platform interface for the firebase_crashlytics plugin.
version: 3.6.29
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics_platform_interface
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics_platform_interface

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.1.3'

dependencies:
  _flutterfire_internals:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/_flutterfire_internals
  collection: ^1.15.0
  firebase_core:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: git@gitlab.com:BC865601/blockcorp/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
