name: firebase_app_check_web
description: The web implementation of firebase_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check_web
version: 0.1.2+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.29
  firebase_app_check_platform_interface: ^0.1.0+23
  firebase_core: ^2.29.0
  firebase_core_web: ^2.15.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.3.3
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppCheckWeb
        fileName: firebase_app_check_web.dart
